// Word bank. Add or remove freely — the game reads whatever is here.
// Keys become the category options in the lobby dropdown automatically.

module.exports = {
  objects: [
    "couch", "toaster", "umbrella", "guitar", "microscope", "vacuum cleaner",
    "lawnmower", "kettle", "wallet", "telescope", "skateboard", "chandelier",
    "fire extinguisher", "sewing machine", "shopping cart", "typewriter",
    "hammock", "backpack", "mousetrap", "chessboard", "wheelbarrow", "compass",
    "candle", "helmet", "ladder", "mirror", "stapler", "trampoline",
    "harmonica", "binoculars", "hourglass", "toolbox", "raincoat", "anchor",
    "piano", "suitcase", "flashlight", "birdcage", "dartboard", "kite",
    "megaphone", "thermometer", "wheelchair", "windmill",
    // + 20 more
    "treadmill", "juggling pins", "snow globe", "accordion",
    "pogo stick", "cash register", "grandfather clock", "surfboard",
    "chainsaw", "record player", "fishing rod", "revolving door",
    "metal detector", "parachute", "bear trap", "disco ball",
    "wind chime", "crystal ball", "straitjacket", "hot air balloon",
  ],
  places: [
    "airport", "casino", "hospital", "submarine", "movie theater", "beach",
    "library", "gym", "space station", "pirate ship", "art museum", "bank vault",
    "amusement park", "zoo", "ski resort", "police station", "supermarket",
    "cemetery", "rooftop bar", "subway station", "greenhouse", "courtroom",
    "recording studio", "lighthouse", "campground", "bowling alley", "farm",
    "cruise ship", "dentist's office", "hotel lobby", "aquarium", "vineyard",
    "military base", "car wash", "haunted house", "train station", "prison",
    "swimming pool", "castle", "laboratory", "circus tent", "bakery",
    "nightclub", "airplane cabin",
    // + 20 more
    "volcano", "desert island", "monastery", "morgue",
    "escape room", "planetarium", "sewer", "boxing ring",
    "wax museum", "nuclear bunker", "petting zoo", "opera house",
    "junkyard", "ice rink", "cave", "food truck",
    "barber shop", "waterfall", "attic", "construction site",
  ],
  jobs: [
    "surgeon", "barista", "pilot", "plumber", "firefighter", "chef", "lawyer",
    "farmer", "astronaut", "librarian", "tattoo artist", "bus driver",
    "wedding planner", "lifeguard", "beekeeper", "translator", "archaeologist",
    "flight attendant", "electrician", "veterinarian", "bodyguard", "journalist",
    "referee", "locksmith", "sculptor", "dentist", "accountant", "park ranger",
    "stunt double", "hairdresser", "mail carrier", "auctioneer", "clown",
    "sommelier", "detective", "welder", "nanny", "cartographer", "diver",
    "magician", "butcher", "architect",
    // + 20 more
    "mortician", "air traffic controller", "ghostwriter", "puppeteer",
    "sniper", "florist", "bounty hunter", "meteorologist",
    "taxidermist", "priest", "crossing guard", "zookeeper",
    "blacksmith", "therapist", "food critic", "storm chaser",
    "cowboy", "professor", "bartender", "dog walker",
  ],
  animals: [
    "penguin", "octopus", "kangaroo", "hedgehog", "flamingo", "sloth", "camel",
    "chameleon", "walrus", "raccoon", "peacock", "jellyfish", "porcupine",
    "armadillo", "otter", "vulture", "gorilla", "dolphin", "scorpion", "moose",
    "koala", "crocodile", "hummingbird", "bat", "hyena", "swan", "lobster",
    "meerkat", "panda", "eagle", "snail", "wolf", "seahorse", "rhinoceros",
    "owl", "ferret", "toucan", "starfish", "llama", "beaver",
    // + 20 more
    "platypus", "tarantula", "narwhal", "sea turtle",
    "cheetah", "goat", "pelican", "chimpanzee",
    "iguana", "hippopotamus", "skunk", "shark",
    "praying mantis", "ostrich", "bison", "lemur",
    "cobra", "woodpecker", "orca", "firefly",
  ],
  food: [
    "sushi", "pancakes", "lasagna", "popcorn", "ramen", "cheesecake", "tacos",
    "watermelon", "croissant", "fried chicken", "hummus", "pineapple",
    "spaghetti", "donut", "curry", "grilled cheese", "oysters", "pretzel",
    "burrito", "waffles", "clam chowder", "kebab", "mashed potatoes", "olives",
    "cotton candy", "dumplings", "bacon", "gelato", "pizza", "avocado",
    "meatloaf", "pho", "bagel", "paella", "smoothie", "garlic bread",
    "s'mores", "risotto", "falafel", "toast",
    // + 20 more
    "escargot", "peanut butter", "caviar", "shawarma",
    "corn dog", "tiramisu", "cereal", "biryani",
    "nachos", "sardines", "macarons", "pickles",
    "beef jerky", "churros", "sauerkraut", "lobster roll",
    "wonton soup", "banana bread", "deviled eggs", "chili",
  ],
};
